version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: AppPython
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: martinez
    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:martinez@postgres:5432/AppPython

volumes:
  postgres_data:
